Dodaj do repozytorium plik konfiguracyjny config.yml w nowo utworzonym folderze .circleci : 

mkdir .circleci 

cd .circleci 

touch config.yml 

Otwórz plik config.yml i dodaj następujacą konfigurację: 

 

version: 2.1 

 

jobs: 

  build-and-test:  

    machine: 

      image: ubuntu-2004:202104-01 

        

    steps: 

      - checkout 

	- run: make lint

      - run: make deps 

      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test 